on:
  release:
    types: [created, edited]

jobs:
  release_windows:
    runs-on: ubuntu-latest
    steps:
      - name: download windows
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          file: ClickMeGodot_Win.zip
        env:
          GITHUB_TOKEN: "${{ secrets.EXPORT_GITHUB_TOKEN }}"
      - name: release windows
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: windows
          ITCH_GAME: click-me-godot
          ITCH_USER: GrandInquisitor
          PACKAGE: ClickMeGodot_Win.zip
  release_linux:
    runs-on: ubuntu-latest
    steps:
      - name: download linux
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          file: ClickMeGodot_LinuxX11.zip
        env:
          GITHUB_TOKEN: "${{ secrets.EXPORT_GITHUB_TOKEN }}"
      - name: release linux
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: linux
          ITCH_GAME: click-me-godot
          ITCH_USER: GrandInquisitor
          PACKAGE: ClickMeGodot_LinuxX11.zip
  release_html5:
    runs-on: ubuntu-latest
    steps:
      - name: download html5
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          file: ClickMeGodot_HTML5.zip
        env:
          GITHUB_TOKEN: "${{ secrets.EXPORT_GITHUB_TOKEN }}"
      - name: release html5
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: html
          ITCH_GAME: click-me-godot
          ITCH_USER: GrandInquisitor
          PACKAGE: ClickMeGodot_HTML5.zip